<script lang="ts">
  import { onMount } from 'svelte';
  import { wizard } from '$lib/stores/wizard';
  import { generateKeyPair } from '$lib/nostr';
  import { hexToNpub } from '$lib/nip46';

  let keyPair = $wizard.keyPair;
  let copied = { npub: false, nsec: false };
  let acknowledged = false;
  let downloaded = false;

  function downloadKeys() {
    if (!keyPair) return;

    const content = `Your Nostr Keys
================

PUBLIC KEY (share this):
${keyPair.npub}

SECRET KEY (keep this private!):
${keyPair.nsec}

----------------
Generated by Insta to Primal
https://instatoprimal.com

IMPORTANT: Store this file securely!
Anyone with your secret key can post as you.
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'nostr-keys.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    downloaded = true;
  }

  $: isNip46Mode = $wizard.authMode === 'nip46';
  $: nip46Npub = $wizard.nip46Pubkey ? hexToNpub($wizard.nip46Pubkey) : '';

  onMount(() => {
    if (!isNip46Mode && !keyPair) {
      keyPair = generateKeyPair();
      wizard.setKeyPair(keyPair);
    }
  });

  async function copyToClipboard(text: string, type: 'npub' | 'nsec') {
    await navigator.clipboard.writeText(text);
    copied[type] = true;
    setTimeout(() => {
      copied[type] = false;
    }, 2000);
  }

  function handleContinue() {
    if (!isNip46Mode && (!acknowledged || !downloaded)) return;
    wizard.setStep('videos');
  }

  function handleBack() {
    wizard.setStep('handle');
  }
</script>

<div class="keys-step">
  {#if isNip46Mode}
    <div class="hero-section">
      <div class="success-badge">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <path d="M20 6L9 17l-5-5"/>
        </svg>
      </div>
      <h2>Connected to Primal</h2>
      <p class="subtitle">Your videos will be posted to your existing Nostr identity</p>
    </div>

    <div class="identity-card">
      <div class="identity-header">
        <span class="label">Your Public Key</span>
        <button class="copy-btn" on:click={() => copyToClipboard(nip46Npub, 'npub')}>
          {#if copied.npub}
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M20 6L9 17l-5-5"/>
            </svg>
            Copied
          {:else}
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
              <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
            </svg>
            Copy
          {/if}
        </button>
      </div>
      <code class="pubkey">{nip46Npub}</code>
    </div>

    <div class="info-banner">
      <svg class="info-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10"/>
        <path d="M12 16v-4M12 8h.01"/>
      </svg>
      <div class="info-content">
        <strong>Remote Signing</strong>
        <p>Your secret key stays safely in your Primal app. Keep this browser tab open during migration.</p>
      </div>
    </div>

    <div class="actions">
      <button class="secondary-btn" on:click={handleBack}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M19 12H5M12 19l-7-7 7-7"/>
        </svg>
        Back
      </button>
      <button class="primary-btn" on:click={handleContinue}>
        Select Videos
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M5 12h14M12 5l7 7-7 7"/>
        </svg>
      </button>
    </div>
  {:else}
    <div class="hero-section">
      <h2>Save your Nostr keys</h2>
      <p class="subtitle">These keys are your identity on Nostr. Store them securely.</p>
    </div>

    {#if keyPair}
      <div class="keys-container">
        <div class="key-card public">
          <div class="key-header">
            <div class="key-label">
              <span class="badge public">Public</span>
              <span class="key-name">npub</span>
            </div>
            <button class="copy-btn" on:click={() => copyToClipboard(keyPair.npub, 'npub')}>
              {#if copied.npub}
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M20 6L9 17l-5-5"/>
                </svg>
              {:else}
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                  <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                </svg>
              {/if}
            </button>
          </div>
          <code class="key-value">{keyPair.npub}</code>
          <span class="key-hint">Share this with others to find you</span>
        </div>

        <div class="key-card secret">
          <div class="key-header">
            <div class="key-label">
              <span class="badge secret">Secret</span>
              <span class="key-name">nsec</span>
            </div>
            <button class="copy-btn" on:click={() => copyToClipboard(keyPair.nsec, 'nsec')}>
              {#if copied.nsec}
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M20 6L9 17l-5-5"/>
                </svg>
              {:else}
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                  <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                </svg>
              {/if}
            </button>
          </div>
          <code class="key-value">{keyPair.nsec}</code>
          <span class="key-hint warning">Never share this with anyone!</span>
        </div>
      </div>

      <button class="download-btn" on:click={downloadKeys}>
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
          <polyline points="7 10 12 15 17 10"/>
          <line x1="12" y1="15" x2="12" y2="3"/>
        </svg>
        {#if downloaded}
          Downloaded!
        {:else}
          Download Keys File
        {/if}
      </button>

      <div class="warning-banner">
        <svg class="warning-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
          <line x1="12" y1="9" x2="12" y2="13"/>
          <line x1="12" y1="17" x2="12.01" y2="17"/>
        </svg>
        <p>Your secret key is like a password. Anyone with it can post as you. Store it in a password manager.</p>
      </div>

      <label class="acknowledge-box" class:disabled={!downloaded}>
        <div class="checkbox-wrapper">
          <input type="checkbox" bind:checked={acknowledged} disabled={!downloaded} />
          <div class="custom-checkbox">
            {#if acknowledged}
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3">
                <path d="M20 6L9 17l-5-5"/>
              </svg>
            {/if}
          </div>
        </div>
        <span>I have downloaded and saved my keys securely</span>
      </label>

      <div class="actions">
        <button class="secondary-btn" on:click={handleBack}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M19 12H5M12 19l-7-7 7-7"/>
          </svg>
          Back
        </button>
        <button class="primary-btn" disabled={!downloaded || !acknowledged} on:click={handleContinue}>
          Select Videos
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M5 12h14M12 5l7 7-7 7"/>
          </svg>
        </button>
      </div>
    {/if}
  {/if}
</div>

<style>
  .keys-step {
    max-width: 560px;
    margin: 0 auto;
  }

  .hero-section {
    text-align: center;
    margin-bottom: 2rem;
  }

  .success-badge {
    width: 3.5rem;
    height: 3.5rem;
    background: linear-gradient(135deg, var(--success), #00A855);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    margin: 0 auto 1rem;
  }

  h2 {
    font-size: 1.5rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
    letter-spacing: -0.02em;
  }

  .subtitle {
    color: var(--text-secondary);
    font-size: 0.9375rem;
  }

  .identity-card {
    background: var(--bg-tertiary);
    border: 1px solid var(--success);
    border-radius: 0.875rem;
    padding: 1.25rem;
    margin-bottom: 1.5rem;
  }

  .identity-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.75rem;
  }

  .label {
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text-muted);
    font-weight: 600;
  }

  .pubkey {
    display: block;
    font-size: 0.75rem;
    word-break: break-all;
    background: var(--bg-primary);
    padding: 0.75rem;
    border-radius: 0.5rem;
    color: var(--text-secondary);
    font-family: 'SF Mono', Monaco, monospace;
  }

  .copy-btn {
    display: flex;
    align-items: center;
    gap: 0.375rem;
    padding: 0.375rem 0.75rem;
    background: transparent;
    border: 1px solid var(--border-light);
    border-radius: 0.5rem;
    color: var(--text-secondary);
    font-size: 0.75rem;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .copy-btn:hover {
    border-color: var(--accent);
    color: var(--accent);
  }

  .info-banner {
    display: flex;
    gap: 1rem;
    padding: 1rem 1.25rem;
    background: rgba(var(--accent-rgb), 0.1);
    border: 1px solid rgba(var(--accent-rgb), 0.2);
    border-radius: 0.75rem;
    margin-bottom: 2rem;
  }

  .info-icon {
    flex-shrink: 0;
    color: var(--accent);
    margin-top: 0.125rem;
  }

  .info-content strong {
    display: block;
    margin-bottom: 0.25rem;
    color: var(--accent);
    font-size: 0.875rem;
  }

  .info-content p {
    font-size: 0.8125rem;
    color: var(--text-secondary);
    margin: 0;
    line-height: 1.5;
  }

  .keys-container {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin-bottom: 1.5rem;
  }

  .key-card {
    background: var(--bg-tertiary);
    border: 1px solid var(--border);
    border-radius: 0.875rem;
    padding: 1.25rem;
  }

  .key-card.secret {
    border-color: var(--warning);
  }

  .key-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.75rem;
  }

  .key-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .badge {
    font-size: 0.625rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
    font-weight: 600;
  }

  .badge.public {
    background: rgba(var(--success-rgb), 0.2);
    color: var(--success);
  }

  .badge.secret {
    background: rgba(255, 176, 32, 0.2);
    color: var(--warning);
  }

  .key-name {
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--text-secondary);
  }

  .key-value {
    display: block;
    font-size: 0.75rem;
    word-break: break-all;
    background: var(--bg-primary);
    padding: 0.75rem;
    border-radius: 0.5rem;
    color: var(--text-primary);
    font-family: 'SF Mono', Monaco, monospace;
    margin-bottom: 0.5rem;
  }

  .key-hint {
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .key-hint.warning {
    color: var(--warning);
  }

  .download-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.625rem;
    width: 100%;
    padding: 1rem;
    background: var(--accent-gradient);
    border: none;
    border-radius: 0.75rem;
    color: white;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
    margin-bottom: 1.5rem;
  }

  .download-btn:hover {
    transform: translateY(-1px);
    box-shadow: 0 4px 20px rgba(var(--accent-rgb), 0.4);
  }

  .warning-banner {
    display: flex;
    gap: 1rem;
    padding: 1rem 1.25rem;
    background: rgba(255, 176, 32, 0.1);
    border: 1px solid rgba(255, 176, 32, 0.3);
    border-radius: 0.75rem;
    margin-bottom: 1.5rem;
  }

  .warning-icon {
    flex-shrink: 0;
    color: var(--warning);
  }

  .warning-banner p {
    font-size: 0.875rem;
    color: var(--text-secondary);
    margin: 0;
    line-height: 1.5;
  }

  .acknowledge-box {
    display: flex;
    align-items: center;
    gap: 0.875rem;
    padding: 1rem 1.25rem;
    background: var(--bg-tertiary);
    border: 1px solid var(--border);
    border-radius: 0.75rem;
    cursor: pointer;
    margin-bottom: 2rem;
    transition: border-color 0.2s ease;
  }

  .acknowledge-box:hover:not(.disabled) {
    border-color: var(--border-light);
  }

  .acknowledge-box.disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .checkbox-wrapper {
    position: relative;
  }

  .checkbox-wrapper input {
    position: absolute;
    opacity: 0;
    width: 0;
    height: 0;
  }

  .custom-checkbox {
    width: 1.375rem;
    height: 1.375rem;
    background: var(--bg-primary);
    border: 2px solid var(--border-light);
    border-radius: 0.375rem;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
  }

  .checkbox-wrapper input:checked + .custom-checkbox {
    background: var(--accent);
    border-color: var(--accent);
    color: white;
  }

  .acknowledge-box span {
    font-size: 0.9375rem;
    color: var(--text-primary);
  }

  .actions {
    display: flex;
    gap: 1rem;
  }

  .secondary-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.875rem 1.25rem;
    background: transparent;
    border: 1px solid var(--border-light);
    border-radius: 0.75rem;
    color: var(--text-primary);
    font-size: 0.9375rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .secondary-btn:hover {
    border-color: var(--text-secondary);
  }

  .primary-btn {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.875rem 1.5rem;
    background: var(--accent-gradient);
    border: none;
    border-radius: 0.75rem;
    color: white;
    font-size: 0.9375rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .primary-btn:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 20px rgba(var(--accent-rgb), 0.4);
  }

  .primary-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
  }
</style>
