<script lang="ts">
  import { onMount } from 'svelte';
  import { wizard } from '$lib/stores/wizard';
  import { generateKeyPair } from '$lib/nostr';
  import { hexToNpub } from '$lib/nip46';

  let keyPair = $wizard.keyPair;
  let copied = { npub: false, nsec: false };
  let downloaded = false;

  function downloadKeys() {
    if (!keyPair) return;

    const content = `Your Primal Key
================

This is your login key for Primal. Keep it safe!

PRIMAL KEY:
${keyPair.nsec}

----------------
Generated by Own Your Posts
https://ownyourposts.com

HOW TO USE:
1. Download the Primal app (iOS or Android)
2. Tap "Login" then "Use login key"
3. Paste your Primal Key above

IMPORTANT: This key is like a password.
Anyone with it can access your account.
Store it somewhere safe!
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'primal-key.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    downloaded = true;
  }

  $: isNip46Mode = $wizard.authMode === 'nip46';
  $: nip46Npub = $wizard.nip46Pubkey ? hexToNpub($wizard.nip46Pubkey) : '';

  onMount(() => {
    console.log('KeysStep mounted, isNip46Mode:', isNip46Mode, 'keyPair:', !!keyPair, 'authMode:', $wizard.authMode);
    if (!isNip46Mode && !keyPair) {
      keyPair = generateKeyPair();
      wizard.setKeyPair(keyPair);
    }
  });

  async function copyToClipboard(text: string, type: 'npub' | 'nsec') {
    await navigator.clipboard.writeText(text);
    copied[type] = true;
    setTimeout(() => {
      copied[type] = false;
    }, 2000);
  }

  function handleContinue() {
    console.log('KeysStep handleContinue called, isNip46Mode:', isNip46Mode, 'downloaded:', downloaded);
    if (!isNip46Mode && !downloaded) {
      console.log('KeysStep: not downloaded yet, returning');
      return;
    }
    console.log('KeysStep: setting step to videos');
    wizard.setStep('videos');
  }

  function handleBack() {
    wizard.setStep('handle');
  }
</script>

<div class="keys-step">
  {#if isNip46Mode}
    <div class="hero-section">
      <div class="success-badge">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <path d="M20 6L9 17l-5-5"/>
        </svg>
      </div>
      <h2>Connected to Primal</h2>
      <p class="subtitle">Your videos will be posted to your existing Nostr identity</p>
    </div>

    <div class="identity-card">
      <div class="identity-header">
        <span class="label">Your Public Key</span>
        <button class="copy-btn" on:click={() => copyToClipboard(nip46Npub, 'npub')}>
          {#if copied.npub}
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M20 6L9 17l-5-5"/>
            </svg>
            Copied
          {:else}
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
              <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
            </svg>
            Copy
          {/if}
        </button>
      </div>
      <code class="pubkey">{nip46Npub}</code>
    </div>

    <div class="info-banner">
      <svg class="info-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10"/>
        <path d="M12 16v-4M12 8h.01"/>
      </svg>
      <div class="info-content">
        <strong>Remote Signing</strong>
        <p>Your secret key stays safely in your Primal app. Keep this browser tab open during publishing.</p>
      </div>
    </div>

    <div class="actions">
      <button class="secondary-btn" on:click={handleBack}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M19 12H5M12 19l-7-7 7-7"/>
        </svg>
        Back
      </button>
      <button class="primary-btn" on:click={handleContinue}>
        Select Videos
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M5 12h14M12 5l7 7-7 7"/>
        </svg>
      </button>
    </div>
  {:else}
    <div class="hero-section">
      <div class="key-icon">
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"/>
        </svg>
      </div>
      <h2>Download your Primal Key</h2>
      <p class="subtitle">This is your login for Primal. Save it somewhere safe!</p>
    </div>

    {#if keyPair}
      <div class="download-section">
        <button class="download-btn" class:downloaded on:click={downloadKeys}>
          {#if downloaded}
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
              <path d="M20 6L9 17l-5-5"/>
            </svg>
            Key Downloaded
          {:else}
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
              <polyline points="7 10 12 15 17 10"/>
              <line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            Download Primal Key
          {/if}
        </button>

        <div class="warning-note">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"/>
            <path d="M12 16v-4M12 8h.01"/>
          </svg>
          <span>You'll need this key to log into Primal later</span>
        </div>
      </div>

      <div class="actions">
        <button class="secondary-btn" on:click={handleBack}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M19 12H5M12 19l-7-7 7-7"/>
          </svg>
          Back
        </button>
        <button class="primary-btn" disabled={!downloaded} on:click={handleContinue}>
          Select Content
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M5 12h14M12 5l7 7-7 7"/>
          </svg>
        </button>
      </div>
    {/if}
  {/if}
</div>

<style>
  .keys-step {
    max-width: 480px;
    margin: 0 auto;
  }

  .hero-section {
    text-align: center;
    margin-bottom: 2rem;
  }

  .key-icon {
    width: 4rem;
    height: 4rem;
    background: var(--accent-gradient);
    border-radius: 1rem;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    margin: 0 auto 1.25rem;
  }

  .success-badge {
    width: 3.5rem;
    height: 3.5rem;
    background: linear-gradient(135deg, var(--success), #00A855);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    margin: 0 auto 1rem;
  }

  h2 {
    font-size: 1.5rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
    letter-spacing: -0.02em;
  }

  .subtitle {
    color: var(--text-secondary);
    font-size: 0.9375rem;
  }

  .identity-card {
    background: var(--bg-tertiary);
    border: 1px solid var(--success);
    border-radius: 0.875rem;
    padding: 1.25rem;
    margin-bottom: 1.5rem;
  }

  .identity-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.75rem;
  }

  .label {
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text-muted);
    font-weight: 600;
  }

  .pubkey {
    display: block;
    font-size: 0.75rem;
    word-break: break-all;
    background: var(--bg-primary);
    padding: 0.75rem;
    border-radius: 0.5rem;
    color: var(--text-secondary);
    font-family: 'SF Mono', Monaco, monospace;
  }

  .copy-btn {
    display: flex;
    align-items: center;
    gap: 0.375rem;
    padding: 0.375rem 0.75rem;
    background: transparent;
    border: 1px solid var(--border-light);
    border-radius: 0.5rem;
    color: var(--text-secondary);
    font-size: 0.75rem;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .copy-btn:hover {
    border-color: var(--accent);
    color: var(--accent);
  }

  .info-banner {
    display: flex;
    gap: 1rem;
    padding: 1rem 1.25rem;
    background: rgba(var(--accent-rgb), 0.1);
    border: 1px solid rgba(var(--accent-rgb), 0.2);
    border-radius: 0.75rem;
    margin-bottom: 2rem;
  }

  .info-icon {
    flex-shrink: 0;
    color: var(--accent);
    margin-top: 0.125rem;
  }

  .info-content strong {
    display: block;
    margin-bottom: 0.25rem;
    color: var(--accent);
    font-size: 0.875rem;
  }

  .info-content p {
    font-size: 0.8125rem;
    color: var(--text-secondary);
    margin: 0;
    line-height: 1.5;
  }

  /* Download section for non-NIP46 */
  .download-section {
    margin-bottom: 2rem;
  }

  .download-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.75rem;
    width: 100%;
    padding: 1.25rem;
    background: var(--accent-gradient);
    border: none;
    border-radius: 0.875rem;
    color: white;
    font-size: 1.125rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .download-btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 24px rgba(var(--accent-rgb), 0.4);
  }

  .download-btn.downloaded {
    background: linear-gradient(135deg, var(--success), #00A855);
  }

  .warning-note {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    margin-top: 1rem;
    color: var(--text-muted);
    font-size: 0.8125rem;
  }

  .warning-note svg {
    flex-shrink: 0;
  }

  .actions {
    display: flex;
    gap: 1rem;
  }

  .secondary-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.875rem 1.25rem;
    background: transparent;
    border: 1px solid var(--border-light);
    border-radius: 0.75rem;
    color: var(--text-primary);
    font-size: 0.9375rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .secondary-btn:hover {
    border-color: var(--text-secondary);
  }

  .primary-btn {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.875rem 1.5rem;
    background: var(--accent-gradient);
    border: none;
    border-radius: 0.75rem;
    color: white;
    font-size: 0.9375rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .primary-btn:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 20px rgba(var(--accent-rgb), 0.4);
  }

  .primary-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
  }
</style>
